"""Change ProgressStartDate and ProgressEndDate to Date

Revision ID: 538730e551e6
Revises: 
Create Date: 2026-03-13 18:08:09.974233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538730e551e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('ProgressStartDate',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('ProgressEndDate',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('ProgressEndDate',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('ProgressStartDate',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
